-- AlterTable
ALTER TABLE "SupplyLabourEntry" ADD COLUMN "fitterForemanQty" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SupplyLabourEntry" ADD COLUMN "fitterForemanHours" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SupplyLabourEntry" ADD COLUMN "fitterForemanRate" DOUBLE PRECISION NOT NULL DEFAULT 1500;
